services:
  web:
    image: ordsky-web
    ports:
      - 80:80
    environment:
      - VITE_SESSION_WEBSOCKET_URL=/ws
      - VITE_SESSION_API_URL=/api/collaborative
      - VITE_COLLECT_BASE_URL=/api/felles
    networks:
      - ordsky

  api:
    image: ordsky-api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALLOWED_ORIGIN=*
      - CORS_POLICY=same-site
      - DB_URL=/app/data/ordsky.db
    volumes:
      - db_data:/app/data
    networks:
      - ordsky

volumes:
  db_data:
    driver: local

networks:
  ordsky:
    driver: bridge
